spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/procurementsystem
    username: bookBorrowed
    password: admin12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: my-spring-boot-simple_project
server:
  port: 8081
